/* eslint-disable no-unused-expressions,jest/valid-expect */
import { defaultAutoCompleteTheme as theme } from '../../../leda/components/AutoComplete/theme';

describe('DateRange', () => {
  let lastConsole
  let stub
  before(() => {
    cy.visit('http://localhost:9000/cypress/daterange')
  })
  it('Delimiter', () => {
    cy.name('firstDatePicker')
      .parents('div.demo-story')
      .parent()
      .find('.daterange-delimiter')
      .should('have.length', 6)
  })
  it.only('MinMaxTest', () => {
    cy.name('MinMaxDatePicker-from')
      .parent()
      .parent()
      .find('.calendar-prev-button i')
      .click()
      .click()
      .parents('.calendar-wrapper.visible')
      .find('div.calendar-date-cell[title="13 апреля 2012"]')
      .click()
      .parent()
      .find('div.calendar-date-cell[title="12 апреля 2012"]')
      .click()
      .name('MinMaxDatePicker-from')
      .should('have.value','12.04.2012')
      .parents('.datepicker-wrapper')
      .parent()
      .name('MinMaxDatePicker-to')
      .parent()
      .parent()
      .find('.calendar-prev-button')
      .click()
      .click()
      .parents('.calendar-wrapper.visible')
      .find('div.calendar-date-cell.disabled-date')
      .contains('11')
      .should('be.exist')
      .parents('.calendar-wrapper.visible')
      .find('div.calendar-date-cell.disabled-date')
      .should('have.length', 19)
      .name('MinMaxDatePicker-to')
      .parent()
      .parent()
      .find('div.calendar-date-cell[title="25 апреля 2012"]')
      .click()
      .parent()
      .find('div.calendar-date-cell[title="26 апреля 2012"]')
      .click()
      .name('MinMaxDatePicker-from')
      .parent()
      .parent()
      .find('div.calendar-date-cell.disabled-date')
      .contains('27')
      .should('be.exist')
      .parents('.calendar-wrapper.visible')
      .find('div.calendar-date-cell.disabled-date')
      .should('have.length', 18)
  })
})