/* eslint-disable key-spacing */
export const defaultCalendarTheme = {
  buttonDisabled:         'ld-calendar-button-disabled',
  dateCell:               'ld-calendar-date',
  dateCellActive:         'ld-calendar-date-active',
  dateCellDayOff:         'ld-calendar-date-day-off',
  dateCellDifferentMonth: 'ld-calendar-date-different-month',
  dateCellDisabled:       'ld-calendar-date-disabled',
  dateCellSelected:       'ld-calendar-date-selected',
  dateCellToday:          'ld-calendar-date-today',
  dateRow:                'ld-calendar-date-row',
  dateView:               'ld-calendar-date-view',
  footer:                 'ld-calendar-footer',
  header:                 'ld-calendar-header',
  monthCell:              'ld-calendar-month-cell',
  monthCellActive:        'ld-calendar-month-cell-active',
  monthCellDisabled:      'ld-calendar-month-cell-disabled',
  monthRow:               'ld-calendar-month-row',
  monthView:              'ld-calendar-month-view',
  nextButton:             'ld-calendar-next-button',
  nextIcon:               'ld-calendar-next-icon',
  prevButton:             'ld-calendar-prev-button',
  prevIcon:               'ld-calendar-prev-icon',
  standalone:             'ld-calendar-standalone',
  title:                  'ld-calendar-title',
  titleDisabled:          'ld-calendar-title-disabled',
  weekDay:                'ld-calendar-week-day',
  weekDaysRow:            'ld-calendar-week-days-row',
  wrapper:                'ld-calendar-wrapper',
  wrapperTop:             'ld-calendar-top',
  wrapperRight:           'ld-calendar-right',
  yearCell:               'ld-calendar-year-cell',
  yearCellActive:         'ld-calendar-year-cell-active',
  yearCellDisabled:       'ld-calendar-year-cell-disabled',
  yearCellDifferentDecade:'ld-calendar-year-cell-different-decade',
  yearRow:                'ld-calendar-year-row',
  yearView:               'ld-calendar-year-view',
};
/* eslint-enable key-spacing */
